### ISSUE TITLE
Synatx Error

### ISSUE THREAD

**Issue by Greenaxio** [SpiderLabs/social_mapper#4]
Syntax Error in line 111.

File "social_mapper.py", line 111
    print "Facebook Check %i/%i : %s" % (count,ammount,person.full_name)
                                    ^
SyntaxError: invalid syntax

**Comment by YvdW** [comment]
I'm having the same issue. Did you also get this error when installing? 
Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: Pillow, numpy, Click, dlib, face-recognition, pytz, django, scipy, six, python-dateut
il, cycler, kiwisolver, pyparsing, matplotlib, cloudpickle, toolz, dask, decorator, networkx, PyWavelets, scikit-ima
ge, scikit-learn, colorama, backcall, win-unicode-console, pickleshare, simplegeneric, wcwidth, prompt-toolkit, pygm
ents, ipython-genutils, traitlets, parso, jedi, ipython
  Running setup.py install for dlib ... error
    Complete output from command

That's not the full error, just a little piece because the full error is much longer. Then when I try to run the script I get the same error as you.

**Comment by YvdW** [comment]
Hi Greenaxio, I see you closed this issue. What solved it for you after all?

**Comment by Greenaxio** [comment]
I used the wrong Python version, but it's not an Issue because it says which to use in the README
