### ISSUE TITLE
[Feature request] Add parameters && More

### ISSUE THREAD

**Issue by N1nj4Turtl3** [SpiderLabs/social_mapper#52]
Hello,

As I did not find any feature request tab, I'm posting this here.
I have some suggestions to improve this fabulous project... :)

1. 

> 
> Add more parameters to the search in order to have more accurate results and limit false positive.
> I though for example to add specific tag like the following:
> - Country
> - State/region
> - City
> - Facebook page or personal people profile page (only search in personal people profile page and conversely)
> - Search in public post (if the target have a private profile, then there will have no result, but if the target posted comments or whatever on public page, this could be used to trace back to the profile target page)
> - Known email address
> - ...

2. 

> Another suggestion will be to be able to search directly with image on search engine using the integrated facial recognition, this could lead to also have result whenever the target is on any social network(even if it's not supported yet by the tool) or not.
> For example, on my test, people had "private" mode on their profile, which lead to no result with this tool (you have to be a friend of a friend to find these guys), but using something like an image search with facial recognition, could be used to search for similar people's photo on the internet, where ever the photo is hosted. Usually this could lead to improve the data about one target, and potentially link to the target many post or internet activities (can be use to enhance the phishing approach). If the target is a football fan, then create a dedicated phishing mail talking about football for example.

3. 

> Another idea I had, maybe not the best, but well it could be interesting to talk about it.
> Sometime I used the people search engine pipl.com, which is very useful to find people online (I'm using it without paying, so I have limited results but it works pretty well most of the time).
> Maybe a function could be added to correlate the results of SocialMapper with the results of pipl (or any other similar tool if you know other one which deserve to have a look at it).

4. 

> And for finish (for today at least), add more social network which keep photo as original. Why? For EXIF data... :) (I think that flickr is the case, correct me if I'm wrong, maybe G+ can do that also but I'm not sure at all, and actually G+ is not the most used SN...)

I know that mean a lot of work to do, but even it's not possible for now, these features could be added to the to do list for later. :)

Again, thanks for the work, and keep going!

**Comment by Green-Wolf** [comment]
Hi @N1nj4Turtl3 

Thank you very much. To address each idea in turn:
1) I would love to do this one day, as doing further matching based on words and fields such as work/educations etc to do better matching or when face recognition fails would be great. 
2) This is a good idea for future expansion, doing a google image search to try and find more info. For this an additional field could be added on the HTML report to store related links.
3) I guess using pipl would be like the above, matches could go in the additional HTML report section. 
4) A Flickr module would be good, i don't think much would be found with it which is why I didn't include it originally, but in the rare case the EXIF for the location data would be great. Again something to add in a Misc additional field in the HTML report. 

All of these ideas are great and would lead to a better tool. However they also seem to be leading away from just a facial recognition and social media mapping tool and into more of an extensive person searching framework. Over time I may try and add some of these, but it believe it would be a significant time investment. As Social Mapper is an open source tool, you are of course welcome, and i would encourage you to take any code in it and reuse it to develop an even better tool or product(Acknowledgements welcome!). We all build of each others ideas & tools in this community :)
