### ISSUE TITLE
Facebook Timeout Error

### ISSUE THREAD

**Issue by LachJones** [SpiderLabs/social_mapper#56]
# Facebook Timeout Error

Command used:
```
./social_mapper.py -f imagefolder -i imagefolder/ -m accurate -gp -tw -ig -fb
```
System: Ubuntu 16.04

-----
## Details
Facebook Login page loads successfully, Login Success, but when running:
```
Facebook Check x/y : Name
```
Returns error: 
```
Facebook session has expired attempting to reestablish...
```
After 3 attempts, then returns
```
Facebook Timeout Error, session has expired and attempts to reestablish have failed
```

**Comment by TheCraftsmen** [comment]
i have the same problem. any solution?

**Comment by TheCraftsmen** [comment]
the problem is in the line 65 of facebookfinder.py

De title is different, this code solve my poblem:

`if(self.driver.title.encode('utf8','replace').split()[-2].startswith(first_name) == False and self.driver.title.encode('utf8','replace').split()[-1].startswith(first_name) == False):`

Example 
the content of self.driver.title is ['B\xc3\xbasqueda', 'en', 'Facebook:', 'Steve', 'Jobs'] you need to get the two lastest values

**Comment by lorenzoromani1983** [comment]
Until today everything was working. But not I get this error:

Facebook check 7/200  Name Surname HTTPSConnectionPool(host='www.facebook.com', port=443): Max retries exceeded with url: /search/async/profile_picture/?fbid=712788588&width=8000&height=8000 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0f4fd48750>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

the network is indeed reachable.

Nothing changed on my system. Not one single file.

**Comment by Green-Wolf** [comment]
Interesting, perhaps facebook is blocking this, i don't think they were very happy about the tool. I'll have a look.

**Comment by Green-Wolf** [comment]
Yeah i thought it might be a connection issue, i've had that with facebook a few times.

**Comment by LachJones** [comment]
**Update**
Issue was related to security settings with external service (Specifically Facebook, but further testing shows similar issues with Instagram and Google too). The service requires further authentication, which was not provided by the script.
Temp Fix: Disable all 2FA and Login security for accounts used with app.

@Green-Wolf : Is there likely to be a fix implemented for this, or is the best approach to use social mapper with an account that we're happy to have no security on?

**Comment by Green-Wolf** [comment]
I would use a throwaway account with no security on it to be honest @LachJones. Thanks for letting me know about it though 👍
