### ISSUE TITLE
-s command doesn't open firefox

### ISSUE THREAD

**Issue by Doctorbadtouch** [SpiderLabs/social_mapper#78]
Hi kinda new with this tool but manage to run it on kali-rolling 2018.3
i removed the firefox ESR and installed firefox 62.0 selenium 14.1 and geckodriver 0.22.0
using `python social_mapper.py -f imagefolder -i ./mytarget -m fast -fb -s` and the program runs log in facebook credentials was ok if i use -t loose i get the right target from the image folder, if i use -t strict i get false results.. at times it prints results from html and csv and at times it returns empty results.
When i installed gecko driver i put it in user/loca/bin folder btw and firefox is located in user/bin

but the main problem i am having at the moment is -s command which doesn't open firefox browser
i tried testing selenium script to test firefox and it is working... might try to downgrade firefox, selenium and geckodriver to check if -s command will work or will try to reinstall everything.

**Comment by Green-Wolf** [comment]
Hi @Doctorbadtouch, try running it with '-m accurate' instead of fast if you are having trouble here. Let me know if you still have problems. Fast mode takes the first result over a threshold, while accurate trys all the top results before picking the best.

**Comment by Doctorbadtouch** [comment]
Hi Green-Wolf i did try running it with -m accurate and tried all the threshold choices -t strict, -t superstrict did use -vv also to check if it will work or not but still i came up empty... haven't tried to downgrade my firefox, selenium and gecko though but i will post a reply here once i've done downgrading firefox 0.62 to 0.60 or 59  and see what the results... i downloaded the apt-get install firefox-mozilla-build by the way if that might help.

**Comment by Green-Wolf** [comment]
Its really strange, firefox should just need to be on a version above 56, which is when headless mode was implemented. In the past when people have had this issue the with -s not showing, its because the whole install is bad, but if the test script is working then it should be ok. 

You mentioned you used firefox-mozilla-build? Have you tried with the readme version:
sudo add-apt-repository ppa:mozillateam/firefox-next && sudo apt update && sudo apt upgrade

For the loose vs strict vs standard, i found it occasionally happens when people have different photos between sites and someone elses looks more like the original photo that theirs, but not on the mass scale that you seem to be experiencing.

I'm a bit flummoxed to be honest with you! Good luck getting it sorted!

**Comment by Doctorbadtouch** [comment]
sudo add-apt-repository ppa:mozillateam/firefox-next && sudo apt update && sudo apt upgrade not working with kali-rolling 2018 i get an error: could not find distribution so i used a different way to install firefox `deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main` added it on my sources.list manually then just apt-get install firefox-mozilla-build and updated it to 62.0.. and oh i am running kali in virtual box.. will also try to re-install everything to see how it works out...

**Comment by Green-Wolf** [comment]
I've only tested it on Mac and Kali on VMware, but i doubt Vitual box is the issue, just mentioning it. Social Mapper has a bunch of dependencies that are easy to get messed up so just keep trying! I'm going to close this, but feel free to keep posting in here if you need help, i'll do what i can. Good luck with the re install!
