### ISSUE TITLE
probably doesn't work modules in instagram and linkedin

### ISSUE THREAD

**Issue by tuyaroroj** [SpiderLabs/social_mapper#86]
Hi! I'm not sure, but I try to find "Bill Gates" in linkedin and instagram and I have no result. I use selenium 3.14, python 2.7.12, latest firefox for ubuntu 16.04. I try different image name. Early I had a positive experience in this sites. What happened now?

**Comment by Green-Wolf** [comment]
Hi @tuyaroroj , are the other sites like facebook working for you?

**Comment by Green-Wolf** [comment]
Hi @tuyaroroj, I'll have a test and see if it works for me, it could be that LinkedIn and Instagram have updated their webpage layout and html class names so the tool needs an update.

**Comment by Green-Wolf** [comment]
Ok i just checked, the instagram issue seems to be because they've added a little notification on login about turning on notifications, if you log into your account and click no, it should work again.

LinkedIn seems to be broken though, so i'm going to look into this. Thank you very much for raising this @tuyaroroj!

**Comment by Green-Wolf** [comment]
Looks like LinkedIn has implemented some code to randomly say no results if you search too much. I will work on a solution

**Comment by tuyaroroj** [comment]
Thank you! I'm happy if my comment it was helpful.
instagram - Every time when I log in I get this window (image below). How to disable it? (exclude log in instagram in my phone).
p.s. What code can hide image? (like forum code [spoiler]) HTML details-summary?

LinkedIn I use not often throught SM.

![instagram_issue](https://user-images.githubusercontent.com/44159548/47019908-69f82f00-d158-11e8-9d30-4d97dd270439.png)

**Comment by Green-Wolf** [comment]
That is strange, if you click both stores and the 'x' does it still come up every login?

**Comment by tuyaroroj** [comment]
> That is strange, if you click both stores and the 'x' does it still come up every login?

Yes. I click 'x' and relogin 3 times. I click both stores and the 'x' 1 times and relogin. It still come up... 
Maybe You add event when sm emulate click 'x'?) Or You haven't this window?

**Comment by Green-Wolf** [comment]
I don't have this window unfortunetly. Do you have a mobile device you can log into instragram with the account you're using? Perhaps that will make the issue go away?

Also i've just pushed a fix for LinkedIn. The issue was 2 fold, firstly they changed the web source so i needed to pull the image links for a different div. Secondly they've added some randomness so occasionally the site will reply with no results when there is actually results. To bypass this i've added a 30 second delay and a recheck, followed by a 5 second delay and a 3rd recheck which manages to bypass this most of the time.

@tuyaroroj would you mind having a go a see if it works for you now? I appreciate the help.

**Comment by tuyaroroj** [comment]
I had some errors when I started sm again. I clone git repo, update system. 
 LinkedIn   - ok
 Facebook - ok
 Twitter      - ok
 GooglePlus - ok
 Instagram - no. I have window, which it's in the way.
 VKontakte - ok
 Weibo - I don't use
 Douban - I don't use

> Also i've just pushed a fix for LinkedIn. 

Thank you!

> Do you have a mobile device you can log into instragram with the account you're using? Perhaps that will make the issue go away?

Yes, I'm sure it is. But I can't log in mobile app. How can I help to fix this little inconvenience?:)

![image](https://user-images.githubusercontent.com/44159548/47162695-bed0ac80-d2f4-11e8-9791-92e26b278217.png)

**Comment by Green-Wolf** [comment]
Hey, if you're interested in writing a fix to instagram, go into the ./modules folder and look at instagram finder. 

In the bit just before the search, you could add an optional check for the popup window and then if it's found close it. 

If you manage to get it working let me know and i'll add you to the contributors list on the main page!

**Comment by Green-Wolf** [comment]
Closing this as it's fixed on all platforms for me

**Comment by Green-Wolf** [comment]
Re opened as I finally encountered this issue on instagram. Thank your for initially raising @tuyaroroj, I should be pushing a fix soon.
